### ISSUE TITLE
3.0.0.14 modify_storagegroup_srdf  regression

### ISSUE THREAD

**Issue by ocarm** [dell/PyU4V#42] opened 2019-07-25 10:18 UTC
Hi,

Function modify_storagegroup_srdf  from replication.py is not working anymore with pyU4V 3.0.0.14

When you try to suspend a replication you get this exception :

message': 'Parameter of type [SgRdfAction] value not one of declared Enum instance values: [Establish, Split, Suspend, Restore, Resume, Failover, Failback, Swap, SetBias, SetMode]

Previous version use to capitalize action to fit VMAX rest-api.

Tag 3.0.0 line 508 payload = {"action": action.capitalize()}
Tag 3.0.0.14 : line 513 payload = {"action": action}

**Comment by MichaelMcAleer** [comment] 2019-07-25 13:12
Hi Olivier,

Can you confirm for me the version of Unisphere you are using? I will try to replicate this behaviour on my end.

**Comment by MichaelMcAleer** [comment] 2019-07-25 13:32
Also, can you send me the parameters your are putting into the function exactly as they are, lower/upper case for example

**Comment by ocarm** [comment] 2019-07-25 13:49
I'm using unisphere 9.0.2.12. I'm not using this function directly. I'm tryng to suspend a srdf asynchronous pair with function suspend_storagegroup_srdf which use it.  This code works fine with 3.0.0.9.
`suspend_options = {consExempt': True}`
`self._conn.replication.suspend_storagegroup_srdf(storagegroup_id=sg_name,rdfg_no=rdf_id,suspend_options=suspend_options)`

**Comment by MichaelMcAleer** [comment] 2019-07-25 14:00
Ok, thanks for the info. We have found what the issue is, the removal of the capitalisation in a previous commit to address issues with some modes broke other modes which were defined in functions such as the suspend_storage_group_srdf you mentioned.

It is a straight forward fix so we will get that added shortly for you.

**Comment by ocarm** [comment] 2019-07-25 14:02
Thanks !

**Comment by MichaelMcAleer** [comment] 2019-07-26 14:40
Hi Olivier,

This issue has been addressed in the most recent pull request: https://github.com/MichaelMcAleer/PyU4V/pull/43

I will keep this issue open until it is merged to master and a new pip package is generated.

Thanks
Michael

**Comment by MichaelMcAleer** [comment] 2019-08-02 13:21
Hi Olivier,

The fix for modifying SG SRDF has been submitted to master, you will see this in driver version 3.0.0.17.

Thanks
Michael

**Closed as completed by MichaelMcAleer** 2019-08-02 13:21 UTC
Labels: bug, fix_submitted
